/*This is an autogenerated file for tileset ChomperSprites*/
using CommonLib.Common;

namespace ContentReader.Tilesets
{
    public static class ChomperSprites
    {
        public static TileInfo RedRight1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "RedRight1");
            }
        }

        public static TileInfo RedDown1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "RedDown1");
            }
        }

        public static TileInfo RedLeft1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "RedLeft1");
            }
        }

        public static TileInfo RedUp1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "RedUp1");
            }
        }

        public static TileInfo RedRight2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "RedRight2");
            }
        }

        public static TileInfo RedDown2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "RedDown2");
            }
        }

        public static TileInfo RedLeft2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "RedLeft2");
            }
        }

        public static TileInfo RedUp2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "RedUp2");
            }
        }

        public static TileInfo YellowRight1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "YellowRight1");
            }
        }

        public static TileInfo YellowDown1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "YellowDown1");
            }
        }

        public static TileInfo YellowLeft1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "YellowLeft1");
            }
        }

        public static TileInfo YellowUp1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "YellowUp1");
            }
        }

        public static TileInfo YellowRight2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "YellowRight2");
            }
        }

        public static TileInfo YellowDown2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "YellowDown2");
            }
        }

        public static TileInfo YellowLeft2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "YellowLeft2");
            }
        }

        public static TileInfo YellowUp2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "YellowUp2");
            }
        }

        public static TileInfo PinkRight1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PinkRight1");
            }
        }

        public static TileInfo PinkDown1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PinkDown1");
            }
        }

        public static TileInfo PinkLeft1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PinkLeft1");
            }
        }

        public static TileInfo PinkUp1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PinkUp1");
            }
        }

        public static TileInfo PinkRight2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PinkRight2");
            }
        }

        public static TileInfo PinkDown2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PinkDown2");
            }
        }

        public static TileInfo PinkLeft2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PinkLeft2");
            }
        }

        public static TileInfo PinkUp2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PinkUp2");
            }
        }

        public static TileInfo GreenRight1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "GreenRight1");
            }
        }

        public static TileInfo GreenDown1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "GreenDown1");
            }
        }

        public static TileInfo GreenLeft1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "GreenLeft1");
            }
        }

        public static TileInfo GreenUp1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "GreenUp1");
            }
        }

        public static TileInfo GreenRight2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "GreenRight2");
            }
        }

        public static TileInfo GreenDown2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "GreenDown2");
            }
        }

        public static TileInfo GreenLeft2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "GreenLeft2");
            }
        }

        public static TileInfo GreenUp2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "GreenUp2");
            }
        }

        public static TileInfo PurpleRight1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PurpleRight1");
            }
        }

        public static TileInfo PurpleDown1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PurpleDown1");
            }
        }

        public static TileInfo PurpleLeft1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PurpleLeft1");
            }
        }

        public static TileInfo PurpleUp1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PurpleUp1");
            }
        }

        public static TileInfo PurpleRight2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PurpleRight2");
            }
        }

        public static TileInfo PurpleDown2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PurpleDown2");
            }
        }

        public static TileInfo PurpleLeft2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PurpleLeft2");
            }
        }

        public static TileInfo PurpleUp2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PurpleUp2");
            }
        }

        public static TileInfo PacRight1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PacRight1");
            }
        }

        public static TileInfo PacDown1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PacDown1");
            }
        }

        public static TileInfo PacLeft1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PacLeft1");
            }
        }

        public static TileInfo PacUp1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PacUp1");
            }
        }

        public static TileInfo PacRight2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PacRight2");
            }
        }

        public static TileInfo PacDown2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PacDown2");
            }
        }

        public static TileInfo PacLeft2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PacLeft2");
            }
        }

        public static TileInfo PacUp2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "PacUp2");
            }
        }

        public static TileInfo BlueGhost1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "BlueGhost1");
            }
        }

        public static TileInfo WhiteGhost1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "WhiteGhost1");
            }
        }

        public static TileInfo GhostEyes1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "GhostEyes1");
            }
        }

        public static TileInfo EmptySquare
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "EmptySquare");
            }
        }

        public static TileInfo BlueGhost2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "BlueGhost2");
            }
        }

        public static TileInfo WhiteGhost2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "WhiteGhost2");
            }
        }

        public static TileInfo GhostEyes2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "GhostEyes2");
            }
        }

        public static TileInfo GreySquare
        {
            get
            {
                return TilesetReader.GetSprite("ChomperSprites", "GreySquare");
            }
        }

    }
}
