
/*This is an autogenerated file for tileset ChomperMazeTiles*/
using CommonLib.Common;

namespace ContentReader.Tilesets
{
    public static class ChomperMazeTiles
    {
        public static TileInfo UpperLeftEmpty
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "UpperLeftEmpty");
            }
        }

        public static TileInfo MiddleLeftEmpty
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "MiddleLeftEmpty");
            }
        }

        public static TileInfo LowerLeftEmpty
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "LowerLeftEmpty");
            }
        }

        public static TileInfo UpperMiddleEmpty
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "UpperMiddleEmpty");
            }
        }

        public static TileInfo MiddleMiddleEmpty
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "MiddleMiddleEmpty");
            }
        }

        public static TileInfo LowerMiddleEmpty
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "LowerMiddleEmpty");
            }
        }

        public static TileInfo UpperRightEmpty
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "UpperRightEmpty");
            }
        }

        public static TileInfo MiddleRightEmpty
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "MiddleRightEmpty");
            }
        }

        public static TileInfo LowerRightEmpty
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "LowerRightEmpty");
            }
        }

        public static TileInfo UpperLeftFill
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "UpperLeftFill");
            }
        }

        public static TileInfo MiddleLeftFill
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "MiddleLeftFill");
            }
        }

        public static TileInfo LowerLeftFill
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "LowerLeftFill");
            }
        }

        public static TileInfo UpperMiddleFill
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "UpperMiddleFill");
            }
        }

        public static TileInfo MiddleMiddleFill
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "MiddleMiddleFill");
            }
        }

        public static TileInfo LowerMiddleFill
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "LowerMiddleFill");
            }
        }

        public static TileInfo UpperRightFill
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "UpperRightFill");
            }
        }

        public static TileInfo MiddleRightFill
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "MiddleRightFill");
            }
        }

        public static TileInfo LowerRightFill
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "LowerRightFill");
            }
        }

        public static TileInfo UpperVertical
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "UpperVertical");
            }
        }

        public static TileInfo MiddleVertical
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "MiddleVertical");
            }
        }

        public static TileInfo LowerVertical
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "LowerVertical");
            }
        }

        public static TileInfo LeftHorizontal
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "LeftHorizontal");
            }
        }

        public static TileInfo Fill
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "Fill");
            }
        }

        public static TileInfo BigDot1
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "BigDot1");
            }
        }

        public static TileInfo MiddleHorizontal
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "MiddleHorizontal");
            }
        }

        public static TileInfo BlackOne
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "BlackOne");
            }
        }

        public static TileInfo BigDot2
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "BigDot2");
            }
        }

        public static TileInfo RightHorizontal
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "RightHorizontal");
            }
        }

        public static TileInfo BlackTwo
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "BlackTwo");
            }
        }

        public static TileInfo SmallDot
        {
            get
            {
                return TilesetReader.GetSprite("ChomperMazeTiles", "SmallDot");
            }
        }

    }
}
